language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO=https://github.com/django/django/tarball/master
  - DJANGO=Django==1.6.5

install:
  - pip install $DJANGO flake8 coverage coveralls
  - pip install -e .

script:
  - flake8 --max-line-length=100 --max-complexity=10 --statistics --benchmark wiki
  - coverage run setup.py test
  - coverage report

matrix:
  exclude:
   - python: 2.6
     env: DJANGO=https://github.com/django/django/tarball/master

after_success: coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net#pinax"
    on_success: change
    on_failure: change
    use_notice: true
